spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: iambatman
  jpa:
    generate-ddl: true

server:
  port: 8080
  
spring:
  jpa:
    generate-ddl: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql

hibernate:
  ddl-auto=update

hedvig:
  kafka:
    acks: all
    retries: 3
    bootstrap:
      servers: localhost:9092
      schema:
        registry:
          url: http://localhost:8081