#spring.datasource.url=jdbc:postgresql://localhost:5432/must-rename
#spring.datasource.username=postgres
#spring.datasource.password=hedvig
#spring.datasource.platform=POSTGRESQL

spring.jpa.generate-ddl=true
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
spring.jpa.hibernate.ddl-auto=update

hedvig.kafka.acks=all
hedvig.kafka.retries=3
hedvig.kafka.bootstrap.servers=localhost:9092
hedvig.kafka.schema.registry.url=http://localhost:8081