server:
  port: 4081


management:
  security:
    enabled: false

hedvig:
  gateway:
    url: localhost:8080
  product-pricing:
    url: localhost:4085
  member-service:
    url: localhost:4084
  payment-service:
    url: localhost:4086
  claims-service:
    url: localhost:8080
  waitlist.length: 20

cloud.aws.region.static: eu-west-1

logging:
  level:
    root: WARN
    com.hedvig: INFO
    org:
      hibernate:
      #        stat: DEBUG
      #        SQL: DEBUG
      type:
        descriptor:
          sql:
          #BasicBinder: TRACE
