server:
  port: 4081

cloud.aws.stack.auto: false

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  jackson:
    serialization:
      write_dates_as_timestamps: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

http.connection.timeout: 3000
http.socket.timeout: 3000
http.connection-manager.timeout: 3000
