server:
  port: 4081

cloud.aws.stack.auto: false

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  jackson:
    serialization:
      write_dates_as_timestamps: false

  data:
    redis:
      repositories:
        enabled: false

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

http.connection.timeout: 3000
http.socket.timeout: 3000
http.connection-manager.timeout: 3000

hedvig:
  appleUser:
    phoneNumber: 0000000000
    email: apple@hedvig.com
    password: plainText
    address:
      zipCode: 12345
      city: California
      street: Palo Alto
    firstName: Steve
    lastName: Jobs
    personalNumber: 195590930334
    memberId: 111111111

graphcms:
  url: https://api-euwest.graphcms.com/v1/cjmawd9hw036a01cuzmjhplka/master
  project: BotService

---

spring:
  profiles: production

hedvig:
  notifications:
    enabled: true
    slackUrl: ${HEDVIG_NOTIFICATIONS_SLACK_URL}
