server:
  port: 4081

    
management:
  security:
    enabled: false

hedvig:
  kafka:
    acks: all
    retries: 3
    bootstrap:
      servers: localhost:9092
      schema:
        registry:
          url: http://localhost:8081